"""
Generated from the CGMES 3 files via cimgen: https://github.com/Alliander/uno-cimgen/
"""

from dataclasses import fields
from functools import cached_property
from pydantic.dataclasses import dataclass
from .Base import DataclassConfig, Profile
from .TurbineGovernorDynamics import TurbineGovernorDynamics


@dataclass(config=DataclassConfig)
class GovSteamFV4(TurbineGovernorDynamics):
    """
    Detailed electro-hydraulic governor for steam unit.

    kf1: Frequency bias (reciprocal of droop) (Kf1).  Typical value = 20.
    kf3: Frequency control (reciprocal of droop) (Kf3).  Typical value = 20.
    lps: Maximum positive power error (Lps).  Typical value = 0,03.
    lpi: Maximum negative power error (Lpi).  Typical value = -0,15.
    mxef: Upper limit for frequency correction (MXEF).  Typical value = 0,05.
    mnef: Lower limit for frequency correction (MNEF).  Typical value = -0,05.
    crmx: Maximum value of regulator set-point (Crmx).  Typical value = 1,2.
    crmn: Minimum value of regulator set-point (Crmn).  Typical value = 0.
    kpt: Proportional gain of electro-hydraulic regulator (Kpt).  Typical value = 0,3.
    kit: Integral gain of electro-hydraulic regulator (Kit).  Typical value = 0,04.
    rvgmx: Maximum value of integral regulator (Rvgmx).  Typical value = 1,2.
    rvgmn: Minimum value of integral regulator (Rvgmn).  Typical value = 0.
    svmx: Maximum regulator gate opening velocity (Svmx).  Typical value = 0,0333.
    svmn: Maximum regulator gate closing velocity (Svmn).  Typical value = -0,0333.
    srmx: Maximum valve opening (Srmx).  Typical value = 1,1.
    srmn: Minimum valve opening (Srmn).  Typical value = 0.
    kpp: Proportional gain of pressure feedback regulator (Kpp).  Typical value = 1.
    kip: Integral gain of pressure feedback regulator (Kip).  Typical value = 0,5.
    rsmimx: Maximum value of integral regulator (Rsmimx).  Typical value = 1,1.
    rsmimn: Minimum value of integral regulator (Rsmimn).  Typical value = 0.
    kmp1: First gain coefficient of  intercept valves characteristic (Kmp1).  Typical value = 0,5.
    kmp2: Second gain coefficient of intercept valves characteristic (Kmp2).  Typical value = 3,5.
    srsmp: Intercept valves characteristic discontinuity point (Srsmp).  Typical value = 0,43.
    ta: Control valves rate opening time (Ta) (>= 0).  Typical value = 0,8.
    tc: Control valves rate closing time (Tc) (>= 0).  Typical value = 0,5.
    ty: Control valves servo time constant (Ty) (>= 0).  Typical value = 0,1.
    yhpmx: Maximum control valve position (Yhpmx).  Typical value = 1,1.
    yhpmn: Minimum control valve position (Yhpmn).  Typical value = 0.
    tam: Intercept valves rate opening time (Tam) (>= 0).  Typical value = 0,8.
    tcm: Intercept valves rate closing time (Tcm) (>= 0).  Typical value = 0,5.
    ympmx: Maximum intercept valve position (Ympmx).  Typical value = 1,1.
    ympmn: Minimum intercept valve position (Ympmn).  Typical value = 0.
    y: Coefficient of linearized equations of turbine (Stodola formulation) (Y).  Typical value = 0,13.
    thp: High pressure (HP) time constant of the turbine (Thp) (>= 0).  Typical value = 0,15.
    trh: Reheater  time constant of the turbine (Trh) (>= 0).  Typical value = 10.
    tmp: Low pressure (LP) time constant of the turbine (Tmp) (>= 0).  Typical value = 0,4.
    khp: Fraction  of total turbine output generated by HP part (Khp).  Typical value = 0,35.
    pr1: First value of pressure set point static characteristic (Pr1).  Typical value = 0,2.
    pr2: Second value of pressure set point static characteristic, corresponding to Ps0 = 1,0 PU (Pr2).  Typical value =
      0,75.
    psmn: Minimum value of pressure set point static characteristic (Psmn).  Typical value = 1.
    kpc: Proportional gain of pressure regulator (Kpc).  Typical value = 0,5.
    kic: Integral gain of pressure regulator (Kic).  Typical value = 0,0033.
    kdc: Derivative gain of pressure regulator (Kdc).  Typical value = 1.
    tdc: Derivative time constant of pressure regulator (Tdc) (>= 0).  Typical value = 90.
    cpsmx: Maximum value of pressure regulator output (Cpsmx).  Typical value = 1.
    cpsmn: Minimum value of pressure regulator output (Cpsmn).  Typical value = -1.
    krc: Maximum variation of fuel flow (Krc).  Typical value = 0,05.
    tf1: Time constant of fuel regulation (Tf1) (>= 0).  Typical value = 10.
    tf2: Time constant of steam chest (Tf2) (>= 0).  Typical value = 10.
    tv: Boiler time constant (Tv) (>= 0).  Typical value = 60.
    ksh: Pressure loss due to flow friction in the boiler tubes (Ksh).  Typical value = 0,08.
    """

    kf1: float = 0.0  # Type #PU in CIM
    kf3: float = 0.0  # Type #PU in CIM
    lps: float = 0.0  # Type #PU in CIM
    lpi: float = 0.0  # Type #PU in CIM
    mxef: float = 0.0  # Type #PU in CIM
    mnef: float = 0.0  # Type #PU in CIM
    crmx: float = 0.0  # Type #PU in CIM
    crmn: float = 0.0  # Type #PU in CIM
    kpt: float = 0.0  # Type #PU in CIM
    kit: float = 0.0  # Type #PU in CIM
    rvgmx: float = 0.0  # Type #PU in CIM
    rvgmn: float = 0.0  # Type #PU in CIM
    svmx: float = 0.0  # Type #Float in CIM
    svmn: float = 0.0  # Type #Float in CIM
    srmx: float = 0.0  # Type #PU in CIM
    srmn: float = 0.0  # Type #PU in CIM
    kpp: float = 0.0  # Type #PU in CIM
    kip: float = 0.0  # Type #PU in CIM
    rsmimx: float = 0.0  # Type #PU in CIM
    rsmimn: float = 0.0  # Type #PU in CIM
    kmp1: float = 0.0  # Type #PU in CIM
    kmp2: float = 0.0  # Type #PU in CIM
    srsmp: float = 0.0  # Type #PU in CIM
    ta: int = 0  # Type #Seconds in CIM
    tc: int = 0  # Type #Seconds in CIM
    ty: int = 0  # Type #Seconds in CIM
    yhpmx: float = 0.0  # Type #PU in CIM
    yhpmn: float = 0.0  # Type #PU in CIM
    tam: int = 0  # Type #Seconds in CIM
    tcm: int = 0  # Type #Seconds in CIM
    ympmx: float = 0.0  # Type #PU in CIM
    ympmn: float = 0.0  # Type #PU in CIM
    y: float = 0.0  # Type #PU in CIM
    thp: int = 0  # Type #Seconds in CIM
    trh: int = 0  # Type #Seconds in CIM
    tmp: int = 0  # Type #Seconds in CIM
    khp: float = 0.0  # Type #PU in CIM
    pr1: float = 0.0  # Type #PU in CIM
    pr2: float = 0.0  # Type #PU in CIM
    psmn: float = 0.0  # Type #PU in CIM
    kpc: float = 0.0  # Type #PU in CIM
    kic: float = 0.0  # Type #PU in CIM
    kdc: float = 0.0  # Type #PU in CIM
    tdc: int = 0  # Type #Seconds in CIM
    cpsmx: float = 0.0  # Type #PU in CIM
    cpsmn: float = 0.0  # Type #PU in CIM
    krc: float = 0.0  # Type #PU in CIM
    tf1: int = 0  # Type #Seconds in CIM
    tf2: int = 0  # Type #Seconds in CIM
    tv: int = 0  # Type #Seconds in CIM
    ksh: float = 0.0  # Type #PU in CIM

    def __str__(self) -> str:
        """Returns the string represention of this element."""

        return "\n".join(
            ["class=GovSteamFV4"] + [f"{field.name}={getattr(self, field.name)}" for field in fields(self.__class__)]
        )

    @cached_property
    def possible_profiles(self) -> dict[str, list]:
        """
        A resource can be used by multiple profiles. This is the list of profiles
        where this element or its attributes can be found.
        """
        return {
            # Class itself
            "class": [
                Profile.DY.value,
            ],
            # Attributes
            "kf1": [
                Profile.DY.value,
            ],
            "kf3": [
                Profile.DY.value,
            ],
            "lps": [
                Profile.DY.value,
            ],
            "lpi": [
                Profile.DY.value,
            ],
            "mxef": [
                Profile.DY.value,
            ],
            "mnef": [
                Profile.DY.value,
            ],
            "crmx": [
                Profile.DY.value,
            ],
            "crmn": [
                Profile.DY.value,
            ],
            "kpt": [
                Profile.DY.value,
            ],
            "kit": [
                Profile.DY.value,
            ],
            "rvgmx": [
                Profile.DY.value,
            ],
            "rvgmn": [
                Profile.DY.value,
            ],
            "svmx": [
                Profile.DY.value,
            ],
            "svmn": [
                Profile.DY.value,
            ],
            "srmx": [
                Profile.DY.value,
            ],
            "srmn": [
                Profile.DY.value,
            ],
            "kpp": [
                Profile.DY.value,
            ],
            "kip": [
                Profile.DY.value,
            ],
            "rsmimx": [
                Profile.DY.value,
            ],
            "rsmimn": [
                Profile.DY.value,
            ],
            "kmp1": [
                Profile.DY.value,
            ],
            "kmp2": [
                Profile.DY.value,
            ],
            "srsmp": [
                Profile.DY.value,
            ],
            "ta": [
                Profile.DY.value,
            ],
            "tc": [
                Profile.DY.value,
            ],
            "ty": [
                Profile.DY.value,
            ],
            "yhpmx": [
                Profile.DY.value,
            ],
            "yhpmn": [
                Profile.DY.value,
            ],
            "tam": [
                Profile.DY.value,
            ],
            "tcm": [
                Profile.DY.value,
            ],
            "ympmx": [
                Profile.DY.value,
            ],
            "ympmn": [
                Profile.DY.value,
            ],
            "y": [
                Profile.DY.value,
            ],
            "thp": [
                Profile.DY.value,
            ],
            "trh": [
                Profile.DY.value,
            ],
            "tmp": [
                Profile.DY.value,
            ],
            "khp": [
                Profile.DY.value,
            ],
            "pr1": [
                Profile.DY.value,
            ],
            "pr2": [
                Profile.DY.value,
            ],
            "psmn": [
                Profile.DY.value,
            ],
            "kpc": [
                Profile.DY.value,
            ],
            "kic": [
                Profile.DY.value,
            ],
            "kdc": [
                Profile.DY.value,
            ],
            "tdc": [
                Profile.DY.value,
            ],
            "cpsmx": [
                Profile.DY.value,
            ],
            "cpsmn": [
                Profile.DY.value,
            ],
            "krc": [
                Profile.DY.value,
            ],
            "tf1": [
                Profile.DY.value,
            ],
            "tf2": [
                Profile.DY.value,
            ],
            "tv": [
                Profile.DY.value,
            ],
            "ksh": [
                Profile.DY.value,
            ],
        }
